export const MessageHelper = {
    MessageTypeInfo: "info",
    MessageTypeWarning: "warning",
    MessageTypeSuccess: "success",
    MessageTypeDanger: "danger",
    Save: "Saved Successfully.",
    Update: "Updated Successfully.",
    Delete: "Deleted Successfully.",
    Add: "Added Successfully.",
    Edit: "Edited Successfully.",
    Remove: "Removed Successfully.",
    SaveFail: "Couldn't Saved Successfully.",
    UpdateFail: "Couldn't Updated Successfully.",
    DeleteFail: "Couldn't Deleted Successfully.",
    AddFail: "Couldn't Added Successfully.",
    EditFail: "Couldn't Edited Successfully.",
    RemoveFail: "Couldn't Removed Successfully.",
    FilesUploaded :  "Files Uploaded Successfully.",
    FilesUploadedFail :  "Files Couldn't Uploaded Successfully.",
    FilesNoSelected :  "No Files Selected.",
    FilesAlreadyExists :  "Already Exists. Files Couldn't Uploaded Successfully.",
    NameAlreadyExists :  "Name already taken. Please choose another name.",
    UrlAlreadyExists :  "Url already taken. Please choose another url.",
    AlreadyExists :  "Already Exists.",
    AlreadyAdded :  "Already added one, So you can edit that one.",
    Success: "Successfully.",
    Info: "Please contact your system admin.",
    Warning: "Please contact your system admin.",
    Error: "We are facing some problem while processing the current request. Please try again later.",
    UnhandledError: "We are facing some problem while processing the current request. Please try again later.",
    UnAuthenticated: "You are not authenticated user.",
    NullError: "Requested object could not found.",
    NullReferenceExceptionError: "There are one or more required fields that are missing.",
    IsEmailExists :  "Email already taken. Please choose another email.",
    IsEmailNotExists :  "Email is not taken.",
    DataNotFound: 'Data not found.',
    TokenExpired: 'Token expired.',
    UnAuthorized: 'You are not authorized user.',
    Logout: 'Logout Successfully.',
}

//let save = MessageHelper.Save,